//! The table oscillator (spec 006 Req 10): single-cycle wavetables and short
//! sampled transients, all generated by this code when the engine starts. Nothing
//! comes from any instrument's ROM.
//!
//! `Tables` holds `TABLES` wavetables of `WAVES` waves of `WAVE_LEN` samples each,
//! and a few attack samples. `TableOsc` reads a wave by linear interpolation and
//! moves between waves by position, crossfading or in steps (the PPG's stepped
//! transitions); `SampleOsc` plays an attack, optionally looping its body. A read is
//! a couple of multiplies and no transcendental (ADR-0002); the tables are built in
//! `Tables::new`, never in `render`. The waves are not band-limited: high notes alias,
//! as the instruments they stand for did.

use crate::voice::{TABLE, sine_table};

/// Samples in one cycle of a wave.
pub const WAVE_LEN: usize = 256;
/// Waves in a wavetable.
pub const WAVES: usize = 64;
/// Wavetables.
pub const TABLES: usize = 8;
/// Harmonics a wave is built from: well under half of `WAVE_LEN`.
const HARMONICS: usize = 31;
/// Samples stored per wave: one more than a cycle, so an interpolation never wraps.
const STRIDE: usize = WAVE_LEN + 1;
/// Attack samples.
pub const SAMPLES: usize = 8;

/// The names of the wavetables, in order.
pub const TABLE_NAMES: [&str; TABLES] = [
    "Sweep", "Pulse", "Formant", "Metal", "Organ", "Hollow", "Digital", "Bell",
];

/// The names of the attack samples, in order.
pub const SAMPLE_NAMES: [&str; SAMPLES] = [
    "Chiff", "Pluck", "Bell", "Marimba", "Blow", "Voice", "Thump", "Glass",
];

/// A sampled transient, optionally looping its tail.
pub struct Sample {
    pub data: Vec<f32>,
    /// The pitch the sample was made at, in cycles per sample.
    pub root_inc: f32,
    /// The loop, from `loop_start` up to `loop_end`; `loop_end` 0 plays it once.
    pub loop_start: usize,
    pub loop_end: usize,
}

pub struct Tables {
    waves: Vec<f32>,
    pub samples: Vec<Sample>,
}

/// Seeded noise, so a sample is the same every start.
struct Noise(u32);

impl Noise {
    fn next(&mut self) -> f32 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 17;
        self.0 ^= self.0 << 5;
        (self.0 as f32 / u32::MAX as f32) * 2.0 - 1.0
    }
}

/// The amplitude of each harmonic (1-based in the index + 1) of wave `k` of `table`.
fn spectrum(table: usize, k: usize, amp: &mut [f32; HARMONICS]) {
    let t = k as f32 / (WAVES - 1) as f32;
    for (i, a) in amp.iter_mut().enumerate() {
        let n = (i + 1) as f32;
        *a = match table {
            // A sine that grows harmonics of a saw one by one.
            0 => {
                let upto = 1.0 + t * (HARMONICS as f32 - 1.0);
                (1.0 / n) * (upto - n + 1.0).clamp(0.0, 1.0)
            }
            // A pulse whose width narrows from half to nearly nothing.
            1 => {
                let w = 0.5 - 0.47 * t;
                (std::f32::consts::PI * n * w).sin().abs() / n
            }
            // A saw through a formant that moves from "oo" to "ee".
            2 => {
                let centre = 2.0 + t * 12.0;
                (1.0 / n) * (0.15 + (-((n - centre) / 2.2).powi(2)).exp() * 3.0)
            }
            // Odd harmonics with gaps that move: clangorous, not a ring.
            3 => {
                let gap = 2.0 + (t * 5.0).floor();
                if (i as f32 + 1.0) % gap < 1.0 {
                    0.0
                } else {
                    n.powf(-0.55)
                }
            }
            // Drawbar-like: a few harmonics whose levels trade places.
            4 => {
                let bars = [1.0, 2.0, 3.0, 4.0, 6.0, 8.0];
                bars.iter()
                    .position(|b| (*b - n).abs() < 0.01)
                    .map_or(0.0, |p| {
                        let ph = t * 6.0 + p as f32;
                        0.5 + 0.5 * (ph * 1.7).fract()
                    })
            }
            // Odd harmonics only, giving way to even ones.
            5 => {
                if i % 2 == 0 {
                    (1.0 - t) / n
                } else {
                    t / n
                }
            }
            // A seeded tangle: levels drawn per harmonic, stepped every eight waves.
            6 => {
                let key = (k / 8) as u32;
                let mut x = key.wrapping_mul(0x9E37_79B1) ^ (i as u32).wrapping_mul(0x85EB_CA6B);
                x ^= x >> 15;
                x = x.wrapping_mul(0x2C1B_3C6D);
                x ^= x >> 12;
                ((x & 0xFFFF) as f32 / 65_535.0) / n.sqrt()
            }
            // A bell: partials at 1, 3 and 5.4 growing with the index.
            _ => {
                let near = |r: f32| (-((n - r) / 0.5).powi(2)).exp();
                near(1.0) + t * (0.9 * near(3.0) + 0.7 * near(5.0) + 0.5 * near(8.0))
            }
        };
    }
}

impl Tables {
    pub fn new(sample_rate: f32) -> Tables {
        let sine = sine_table();
        let mut waves = vec![0.0; TABLES * WAVES * STRIDE];
        let mut amp = [0.0_f32; HARMONICS];
        for table in 0..TABLES {
            for k in 0..WAVES {
                spectrum(table, k, &mut amp);
                let base = (table * WAVES + k) * STRIDE;
                let mut peak = 1.0e-6_f32;
                for i in 0..WAVE_LEN {
                    // The sine table has TABLE points per cycle, so harmonic n of
                    // sample i is point n·i·TABLE/WAVE_LEN, wrapped.
                    let mut y = 0.0;
                    for (h, a) in amp.iter().enumerate() {
                        let idx = ((h + 1) * i * (TABLE / WAVE_LEN)) % TABLE;
                        y += a * sine.get(idx).copied().unwrap_or(0.0);
                    }
                    if let Some(w) = waves.get_mut(base + i) {
                        *w = y;
                    }
                    peak = peak.max(y.abs());
                }
                for w in waves.iter_mut().skip(base).take(WAVE_LEN) {
                    *w /= peak;
                }
                let first = waves.get(base).copied().unwrap_or(0.0);
                if let Some(w) = waves.get_mut(base + WAVE_LEN) {
                    *w = first;
                }
            }
        }
        Tables {
            waves,
            samples: make_samples(sample_rate),
        }
    }

    /// Wave `k` of `table`, `WAVE_LEN` samples and a guard; out of range reads silence.
    pub fn wave(&self, table: usize, k: usize) -> &[f32] {
        let base = (table.min(TABLES - 1) * WAVES + k.min(WAVES - 1)) * STRIDE;
        self.waves.get(base..base + STRIDE).unwrap_or(&[])
    }
}

/// One cycle's worth of a read: `phase` 0..1 into a wave, interpolated.
fn read(wave: &[f32], phase: f32) -> f32 {
    let p = phase * WAVE_LEN as f32;
    let i = (p as usize).min(WAVE_LEN - 1);
    let frac = p - i as f32;
    let a = wave.get(i).copied().unwrap_or(0.0);
    let b = wave.get(i + 1).copied().unwrap_or(a);
    a + (b - a) * frac
}

/// A wavetable oscillator: a phase and its step.
#[derive(Clone, Copy, Default)]
pub struct TableOsc {
    phase: f32,
    inc: f32,
}

impl TableOsc {
    /// Set the frequency in cycles per sample.
    pub fn set_increment(&mut self, inc: f32) {
        self.inc = if inc.is_finite() {
            inc.clamp(0.0, 0.5)
        } else {
            0.0
        };
    }

    /// Start from the beginning of a cycle.
    pub fn reset(&mut self) {
        self.phase = 0.0;
    }

    /// One sample of `table` at wave position `pos` (0..1): crossfading between the
    /// two nearest waves, or with `steps` on the nearest one alone.
    pub fn step(&mut self, t: &Tables, table: usize, pos: f32, steps: bool) -> f32 {
        let x = pos.clamp(0.0, 1.0) * (WAVES - 1) as f32;
        let k = x as usize;
        let y = if steps {
            read(t.wave(table, (x + 0.5) as usize), self.phase)
        } else {
            let a = read(t.wave(table, k), self.phase);
            let b = read(t.wave(table, k + 1), self.phase);
            a + (b - a) * (x - k as f32)
        };
        self.phase += self.inc;
        if self.phase >= 1.0 {
            self.phase -= 1.0;
        }
        y
    }
}

/// Plays a `Sample` from its start at a rate, looping where it says to.
#[derive(Clone, Copy, Default)]
pub struct SampleOsc {
    pos: f32,
    done: bool,
}

impl SampleOsc {
    /// Begin again.
    pub fn start(&mut self) {
        self.pos = 0.0;
        self.done = false;
    }

    /// One sample at `inc` cycles per sample of the note, the sample's own pitch being
    /// `root_inc`. Silence once a one-shot has ended.
    pub fn step(&mut self, s: &Sample, inc: f32) -> f32 {
        if self.done || s.root_inc <= 0.0 {
            return 0.0;
        }
        let i = self.pos as usize;
        let frac = self.pos - i as f32;
        let a = s.data.get(i).copied().unwrap_or(0.0);
        let b = s.data.get(i + 1).copied().unwrap_or(a);
        let y = a + (b - a) * frac;
        self.pos += if inc.is_finite() {
            inc / s.root_inc
        } else {
            0.0
        };
        if s.loop_end > s.loop_start && self.pos >= s.loop_end as f32 {
            self.pos -= (s.loop_end - s.loop_start) as f32;
        } else if self.pos >= s.data.len() as f32 {
            self.done = true;
        }
        y
    }
}

/// Our own transients: noise bursts, plucks, partials that die at their own rates,
/// and a looping vowel. Built with `std` trig once, at start.
fn make_samples(sr: f32) -> Vec<Sample> {
    let tau = std::f64::consts::TAU;
    let sr64 = f64::from(sr);
    let mut rng = Noise(0x2545_F491);
    let n_of = |secs: f64| (secs * sr64) as usize;
    let one_shot = |data: Vec<f32>, root_hz: f64| Sample {
        data,
        root_inc: (root_hz / sr64) as f32,
        loop_start: 0,
        loop_end: 0,
    };
    let partials = |ratios: &[(f64, f64, f64)], root: f64, secs: f64| {
        (0..n_of(secs))
            .map(|i| {
                let t = i as f64 / sr64;
                ratios
                    .iter()
                    .map(|(r, amp, decay)| amp * (-t * decay).exp() * (tau * root * r * t).sin())
                    .sum::<f64>() as f32
            })
            .collect::<Vec<f32>>()
    };
    let mut out = Vec::new();
    // 0 Chiff: a breath of band-limited noise over 80 ms.
    let (mut lp, mut hp) = (0.0_f32, 0.0_f32);
    out.push(one_shot(
        (0..n_of(0.09))
            .map(|i| {
                let t = i as f32 / sr;
                let x = rng.next();
                lp += 0.35 * (x - lp);
                hp += 0.05 * (lp - hp);
                (lp - hp) * (-t * 38.0).exp() * 2.2
            })
            .collect(),
        261.63,
    ));
    // 1 Pluck: Karplus-Strong at 220 Hz.
    let period = (sr64 / 220.0).round() as usize;
    let mut line: Vec<f32> = (0..period).map(|_| rng.next()).collect();
    let mut pluck = Vec::with_capacity(n_of(0.7));
    for i in 0..n_of(0.7) {
        let a = line.get(i % period).copied().unwrap_or(0.0);
        let b = line.get((i + 1) % period).copied().unwrap_or(0.0);
        pluck.push(a);
        if let Some(s) = line.get_mut(i % period) {
            *s = 0.497 * (a + b);
        }
    }
    out.push(one_shot(pluck, sr64 / period as f64));
    // 2 Bell, 3 Marimba, 7 Glass: partials that decay at their own rates.
    out.push(one_shot(
        partials(
            &[
                (1.0, 0.6, 3.0),
                (2.76, 0.5, 4.5),
                (5.4, 0.35, 7.0),
                (8.93, 0.25, 11.0),
            ],
            440.0,
            1.2,
        ),
        440.0,
    ));
    let marimba = partials(
        &[(1.0, 0.8, 7.0), (4.0, 0.4, 16.0), (10.0, 0.1, 30.0)],
        261.63,
        0.55,
    );
    // 3 Marimba comes after Bell in the list; 4 Blow and 5 Voice follow below.
    out.push(one_shot(marimba, 261.63));
    // 4 Blow: noise through a band, swelling over 0.3 s.
    let (mut b1, mut b2) = (0.0_f32, 0.0_f32);
    out.push(one_shot(
        (0..n_of(0.35))
            .map(|i| {
                let t = i as f32 / sr;
                let x = rng.next();
                b1 += 0.12 * (x - b1);
                b2 += 0.12 * (b1 - b2);
                (b1 - b2) * 5.0 * (t / 0.25).min(1.0) * (-((t - 0.1).max(0.0)) * 2.0).exp()
            })
            .collect(),
        261.63,
    ));
    // 5 Voice: an "ah" of formant-weighted harmonics, its last 40 periods looped.
    let vp = (sr64 / 220.0).round() as usize;
    let root = sr64 / vp as f64;
    let total = vp * 60;
    let voice: Vec<f32> = (0..total)
        .map(|i| {
            let t = i as f64 / sr64;
            let swell = (t / 0.04).min(1.0);
            (1..=24)
                .map(|h| {
                    let f = root * h as f64;
                    let formant = (-(((f - 800.0) / 260.0).powi(2))).exp()
                        + 0.6 * (-(((f - 1_200.0) / 300.0).powi(2))).exp()
                        + 0.05;
                    formant / h as f64 * (tau * f * t).sin()
                })
                .sum::<f64>() as f32
                * swell as f32
        })
        .collect();
    let peak = voice.iter().fold(1.0e-6_f32, |m, x| m.max(x.abs()));
    out.push(Sample {
        data: voice.iter().map(|x| x / peak * 0.9).collect(),
        root_inc: (root / sr64) as f32,
        loop_start: vp * 20,
        loop_end: vp * 60,
    });
    // 6 Thump: a sine falling from 220 to 55 Hz.
    out.push(one_shot(
        {
            let mut ph = 0.0_f64;
            (0..n_of(0.18))
                .map(|i| {
                    let t = i as f64 / sr64;
                    ph += tau * (55.0 + 165.0 * (-t * 28.0).exp()) / sr64;
                    (ph.sin() * (-t * 14.0).exp()) as f32
                })
                .collect()
        },
        110.0,
    ));
    // 7 Glass: high partials of a struck glass.
    out.push(one_shot(
        partials(
            &[
                (1.0, 0.5, 2.0),
                (2.32, 0.5, 2.6),
                (4.25, 0.4, 3.5),
                (6.63, 0.3, 5.0),
            ],
            880.0,
            1.0,
        ),
        880.0,
    ));
    // Fit every sample inside ±1 (the partial sums are not normalised).
    for s in out.iter_mut() {
        let peak = s.data.iter().fold(1.0e-6_f32, |m, x| m.max(x.abs()));
        if peak > 1.0 {
            for x in s.data.iter_mut() {
                *x /= peak;
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const SR: f32 = 48_000.0;

    /// The frequency in Hz of an oscillator playing wave `k` of `table` at `note`, from
    /// the interpolated times of its upward zero crossings over many cycles.
    fn measured_hz(t: &Tables, table: usize, note: f32) -> f64 {
        let hz = 440.0 * 2.0_f32.powf((note - 69.0) / 12.0);
        let mut osc = TableOsc::default();
        osc.set_increment(hz / SR);
        let n = (SR * 6.0) as usize;
        let out: Vec<f32> = (0..n).map(|_| osc.step(t, table, 0.0, false)).collect();
        let mut times = Vec::new();
        for (i, w) in out.windows(2).enumerate() {
            if w[0] <= 0.0 && w[1] > 0.0 {
                times.push(i as f64 + f64::from(-w[0] / (w[1] - w[0])));
            }
        }
        let cycles = (times.len() - 1) as f64;
        cycles / ((times[times.len() - 1] - times[0]) / f64::from(SR))
    }

    #[test]
    fn every_wave_is_finite_bounded_and_closes_its_cycle() {
        let t = Tables::new(SR);
        for (table, name) in TABLE_NAMES.iter().enumerate() {
            for k in 0..WAVES {
                let w = t.wave(table, k);
                assert_eq!(w.len(), STRIDE);
                assert!(
                    w.iter().all(|x| x.is_finite() && x.abs() <= 1.0 + 1.0e-6),
                    "{table} {k}"
                );
                assert!(
                    w.iter().any(|x| x.abs() > 0.5),
                    "{name} wave {k} has a body"
                );
                assert_eq!(w[0], w[WAVE_LEN], "{table} {k}: the guard closes the cycle");
            }
        }
    }

    /// Spec 006 Req 10: the oscillator's pitch is within a cent from note 24 to 108.
    #[test]
    fn pitch_is_within_a_cent() {
        let t = Tables::new(SR);
        for note in [24.0, 36.0, 48.0, 60.0, 72.0, 84.0, 96.0, 108.0] {
            let want = 440.0 * 2.0_f64.powf((f64::from(note) - 69.0) / 12.0);
            let got = measured_hz(&t, 0, note);
            let cents = 1200.0 * (got / want).log2();
            assert!(cents.abs() < 1.0, "note {note}: {cents} cents");
        }
    }

    /// Moving the position moves between distinct spectra, in every wavetable.
    #[test]
    fn position_moves_between_distinct_spectra() {
        let t = Tables::new(SR);
        let level = |table: usize, k: usize, h: usize| {
            let w = t.wave(table, k);
            let (re, im) = (0..WAVE_LEN).fold((0.0, 0.0), |(re, im), i| {
                let a = std::f64::consts::TAU * (h * i) as f64 / WAVE_LEN as f64;
                (
                    re + f64::from(w[i]) * a.cos(),
                    im + f64::from(w[i]) * a.sin(),
                )
            });
            (re * re + im * im).sqrt()
        };
        for (table, name) in TABLE_NAMES.iter().enumerate() {
            let differs =
                (1..=12).any(|h| (level(table, 0, h) - level(table, WAVES - 1, h)).abs() > 5.0);
            assert!(differs, "{name} does not change along its length");
        }
    }

    #[test]
    fn steps_hold_a_wave_and_crossfades_blend_two() {
        let t = Tables::new(SR);
        let at = |pos: f32, steps: bool| {
            let mut osc = TableOsc::default();
            osc.set_increment(0.01);
            (0..100)
                .map(|_| osc.step(&t, 0, pos, steps))
                .collect::<Vec<f32>>()
        };
        // Just either side of the half-way point between waves 10 and 11.
        let below = 10.49 / (WAVES - 1) as f32;
        let above = 10.51 / (WAVES - 1) as f32;
        assert_eq!(
            at(below, true),
            at(10.0 / (WAVES - 1) as f32, true),
            "stepped: wave 10"
        );
        assert_eq!(
            at(above, true),
            at(11.0 / (WAVES - 1) as f32, true),
            "stepped: wave 11"
        );
        assert_ne!(
            at(below, false),
            at(10.0 / (WAVES - 1) as f32, false),
            "crossfaded: already moving"
        );
        // A position on a wave is that wave, stepped or not.
        let on = 20.0 / (WAVES - 1) as f32;
        let (a, b) = (at(on, false), at(on, true));
        assert!(a.iter().zip(&b).all(|(x, y)| (x - y).abs() < 1.0e-5));
    }

    #[test]
    fn the_samples_are_ours_finite_bounded_and_end_or_loop() {
        let t = Tables::new(SR);
        assert_eq!(t.samples.len(), SAMPLES);
        for (i, s) in t.samples.iter().enumerate() {
            let name = SAMPLE_NAMES[i];
            assert!(s.data.len() > 1_000, "{name}");
            assert!(
                s.data
                    .iter()
                    .all(|x| x.is_finite() && x.abs() <= 1.0 + 1.0e-6),
                "{name}"
            );
            assert!(s.data.iter().any(|x| x.abs() > 0.1), "{name} sounds");
            assert!(s.root_inc > 0.0, "{name}");
            if s.loop_end > 0 {
                assert!(
                    s.loop_start < s.loop_end && s.loop_end <= s.data.len(),
                    "{name}"
                );
            }
        }
        // Played once, a one-shot ends in silence; a looping one never does.
        for (i, s) in t.samples.iter().enumerate() {
            let mut osc = SampleOsc::default();
            osc.start();
            let tail: Vec<f32> = (0..(SR * 3.0) as usize)
                .map(|_| osc.step(s, s.root_inc))
                .collect();
            let quiet = tail.iter().rev().take(2_000).all(|x| x.abs() < 1.0e-6);
            assert_eq!(
                quiet,
                s.loop_end == 0,
                "{} {}",
                SAMPLE_NAMES[i],
                if s.loop_end == 0 {
                    "should end"
                } else {
                    "should loop"
                }
            );
        }
    }

    #[test]
    fn a_sample_plays_an_octave_up_twice_as_fast() {
        let t = Tables::new(SR);
        let s = &t.samples[2];
        let length = |inc: f32| {
            let mut osc = SampleOsc::default();
            osc.start();
            let mut n = 0;
            while n < 400_000 && {
                osc.step(s, inc);
                !osc.done
            } {
                n += 1;
            }
            n as f32
        };
        let (a, b) = (length(s.root_inc), length(2.0 * s.root_inc));
        assert!((a / b - 2.0).abs() < 0.01, "{a} {b}");
    }

    #[test]
    fn bad_increments_are_silent_not_nan() {
        let t = Tables::new(SR);
        let mut osc = TableOsc::default();
        for inc in [f32::NAN, f32::INFINITY, -1.0, 7.0] {
            osc.set_increment(inc);
            assert!((0..1000).all(|_| osc.step(&t, 3, f32::NAN.max(0.3), false).is_finite()));
        }
        let mut so = SampleOsc::default();
        so.start();
        assert!((0..100).all(|_| so.step(&t.samples[0], f32::NAN).is_finite()));
        assert_eq!(t.wave(99, 99).len(), STRIDE, "out-of-range clamps");
    }
}
