/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 46
#define EXTERNAL_TOKEN_COUNT 8
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name = 1,
  anon_sym_LF = 2,
  anon_sym_tempo = 3,
  anon_sym_swing = 4,
  anon_sym_scale = 5,
  anon_sym_setting = 6,
  anon_sym_track = 7,
  anon_sym_samples = 8,
  anon_sym_strip = 9,
  anon_sym_group = 10,
  anon_sym_master = 11,
  anon_sym_clip = 12,
  anon_sym_auto = 13,
  anon_sym_snapshot = 14,
  anon_sym_mod = 15,
  anon_sym_scene = 16,
  anon_sym_arrange = 17,
  anon_sym_loop = 18,
  anon_sym_frag = 19,
  anon_sym_section = 20,
  anon_sym_live = 21,
  anon_sym_bars = 22,
  anon_sym_ramp = 23,
  anon_sym_drums = 24,
  anon_sym_synth = 25,
  anon_sym_sampler = 26,
  anon_sym_voicing = 27,
  sym_param = 28,
  anon_sym_LPAREN = 29,
  sym_number = 30,
  sym_punct = 31,
  sym_rest = 32,
  sym_other = 33,
  sym_pad = 34,
  sym_step = 35,
  sym_dots = 36,
  sym_comment = 37,
  sym__line_start = 38,
  sym__modular_start = 39,
  sym__lane_indent = 40,
  sym__call_lane_indent = 41,
  sym__notes_indent = 42,
  sym__code_indent = 43,
  sym__line_end = 44,
  sym__error_sentinel = 45,
  sym_source_file = 46,
  sym_line = 47,
  sym_modular = 48,
  sym_code = 49,
  sym_lane = 50,
  sym_notes = 51,
  sym__token = 52,
  sym_keyword = 53,
  sym_word = 54,
  sym_call = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_line_repeat1 = 57,
  aux_sym_modular_repeat1 = 58,
  aux_sym_lane_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [anon_sym_LF] = "\n",
  [anon_sym_tempo] = "tempo",
  [anon_sym_swing] = "swing",
  [anon_sym_scale] = "scale",
  [anon_sym_setting] = "setting",
  [anon_sym_track] = "track",
  [anon_sym_samples] = "samples",
  [anon_sym_strip] = "strip",
  [anon_sym_group] = "group",
  [anon_sym_master] = "master",
  [anon_sym_clip] = "clip",
  [anon_sym_auto] = "auto",
  [anon_sym_snapshot] = "snapshot",
  [anon_sym_mod] = "mod",
  [anon_sym_scene] = "scene",
  [anon_sym_arrange] = "arrange",
  [anon_sym_loop] = "loop",
  [anon_sym_frag] = "frag",
  [anon_sym_section] = "section",
  [anon_sym_live] = "live",
  [anon_sym_bars] = "bars",
  [anon_sym_ramp] = "ramp",
  [anon_sym_drums] = "drums",
  [anon_sym_synth] = "synth",
  [anon_sym_sampler] = "sampler",
  [anon_sym_voicing] = "voicing",
  [sym_param] = "param",
  [anon_sym_LPAREN] = "punct",
  [sym_number] = "number",
  [sym_punct] = "punct",
  [sym_rest] = "rest",
  [sym_other] = "other",
  [sym_pad] = "pad",
  [sym_step] = "step",
  [sym_dots] = "dots",
  [sym_comment] = "comment",
  [sym__line_start] = "_line_start",
  [sym__modular_start] = "_modular_start",
  [sym__lane_indent] = "_lane_indent",
  [sym__call_lane_indent] = "_call_lane_indent",
  [sym__notes_indent] = "_notes_indent",
  [sym__code_indent] = "_code_indent",
  [sym__line_end] = "_line_end",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_source_file] = "source_file",
  [sym_line] = "line",
  [sym_modular] = "modular",
  [sym_code] = "code",
  [sym_lane] = "lane",
  [sym_notes] = "notes",
  [sym__token] = "_token",
  [sym_keyword] = "keyword",
  [sym_word] = "word",
  [sym_call] = "call",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_line_repeat1] = "line_repeat1",
  [aux_sym_modular_repeat1] = "modular_repeat1",
  [aux_sym_lane_repeat1] = "lane_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_tempo] = anon_sym_tempo,
  [anon_sym_swing] = anon_sym_swing,
  [anon_sym_scale] = anon_sym_scale,
  [anon_sym_setting] = anon_sym_setting,
  [anon_sym_track] = anon_sym_track,
  [anon_sym_samples] = anon_sym_samples,
  [anon_sym_strip] = anon_sym_strip,
  [anon_sym_group] = anon_sym_group,
  [anon_sym_master] = anon_sym_master,
  [anon_sym_clip] = anon_sym_clip,
  [anon_sym_auto] = anon_sym_auto,
  [anon_sym_snapshot] = anon_sym_snapshot,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_scene] = anon_sym_scene,
  [anon_sym_arrange] = anon_sym_arrange,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_frag] = anon_sym_frag,
  [anon_sym_section] = anon_sym_section,
  [anon_sym_live] = anon_sym_live,
  [anon_sym_bars] = anon_sym_bars,
  [anon_sym_ramp] = anon_sym_ramp,
  [anon_sym_drums] = anon_sym_drums,
  [anon_sym_synth] = anon_sym_synth,
  [anon_sym_sampler] = anon_sym_sampler,
  [anon_sym_voicing] = anon_sym_voicing,
  [sym_param] = sym_param,
  [anon_sym_LPAREN] = sym_punct,
  [sym_number] = sym_number,
  [sym_punct] = sym_punct,
  [sym_rest] = sym_rest,
  [sym_other] = sym_other,
  [sym_pad] = sym_pad,
  [sym_step] = sym_step,
  [sym_dots] = sym_dots,
  [sym_comment] = sym_comment,
  [sym__line_start] = sym__line_start,
  [sym__modular_start] = sym__modular_start,
  [sym__lane_indent] = sym__lane_indent,
  [sym__call_lane_indent] = sym__call_lane_indent,
  [sym__notes_indent] = sym__notes_indent,
  [sym__code_indent] = sym__code_indent,
  [sym__line_end] = sym__line_end,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym_line] = sym_line,
  [sym_modular] = sym_modular,
  [sym_code] = sym_code,
  [sym_lane] = sym_lane,
  [sym_notes] = sym_notes,
  [sym__token] = sym__token,
  [sym_keyword] = sym_keyword,
  [sym_word] = sym_word,
  [sym_call] = sym_call,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_line_repeat1] = aux_sym_line_repeat1,
  [aux_sym_modular_repeat1] = aux_sym_modular_repeat1,
  [aux_sym_lane_repeat1] = aux_sym_lane_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tempo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_swing] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scale] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_setting] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_track] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_samples] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_strip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_group] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_master] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_clip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_auto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_snapshot] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scene] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_arrange] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_frag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_section] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_live] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bars] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ramp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_drums] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_synth] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sampler] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_voicing] = {
    .visible = true,
    .named = false,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_punct] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [sym_other] = {
    .visible = true,
    .named = true,
  },
  [sym_pad] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_dots] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__line_start] = {
    .visible = false,
    .named = true,
  },
  [sym__modular_start] = {
    .visible = false,
    .named = true,
  },
  [sym__lane_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__call_lane_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__notes_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__code_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__line_end] = {
    .visible = false,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_modular] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_lane] = {
    .visible = true,
    .named = true,
  },
  [sym_notes] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_modular_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lane_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 11,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 17,
  [22] = 19,
  [23] = 18,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '~') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12);
      if (lookahead == '!' ||
          lookahead == '"' ||
          lookahead == '&' ||
          (')' <= lookahead && lookahead <= ',') ||
          lookahead == '/' ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '~') ADVANCE(21);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead == '!' ||
          lookahead == '"' ||
          lookahead == '&' ||
          (')' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (('2' <= lookahead && lookahead <= '4') ||
          lookahead == 'X' ||
          lookahead == 'd' ||
          lookahead == 'f' ||
          lookahead == 'o' ||
          lookahead == 'x') ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '~') ADVANCE(21);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead == '!' ||
          lookahead == '"' ||
          lookahead == '&' ||
          ('(' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '~') ADVANCE(21);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead == '!' ||
          lookahead == '"' ||
          lookahead == '&' ||
          (')' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '~') ADVANCE(21);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead == '!' ||
          lookahead == '"' ||
          lookahead == '&' ||
          ('(' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 11:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '~') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12);
      if (lookahead == '!' ||
          lookahead == '"' ||
          lookahead == '&' ||
          ('(' <= lookahead && lookahead <= ',') ||
          lookahead == '/' ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '#' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '#' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_param);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '#' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_punct);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_rest);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_other);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_other);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_pad);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_step);
      if (('2' <= lookahead && lookahead <= '4') ||
          lookahead == 'X' ||
          lookahead == 'd' ||
          lookahead == 'f' ||
          lookahead == 'o' ||
          lookahead == 'x') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_dots);
      if (lookahead == '.') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'g', 6,
        'l', 7,
        'm', 8,
        'r', 9,
        's', 10,
        't', 11,
        'v', 12,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(25);
      if (lookahead == 'c') ADVANCE(26);
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead == 'n') ADVANCE(28);
      if (lookahead == 't') ADVANCE(29);
      if (lookahead == 'w') ADVANCE(30);
      if (lookahead == 'y') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 20:
      if (lookahead == 'v') ADVANCE(42);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(46);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(47);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(48);
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 27:
      if (lookahead == 'c') ADVANCE(50);
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(56);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 35:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(61);
      END_STATE();
    case 38:
      if (lookahead == 'p') ADVANCE(62);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(63);
      END_STATE();
    case 40:
      if (lookahead == 'g') ADVANCE(64);
      END_STATE();
    case 41:
      if (lookahead == 'u') ADVANCE(65);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 43:
      if (lookahead == 'p') ADVANCE(67);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_mod);
      END_STATE();
    case 46:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 47:
      if (lookahead == 'p') ADVANCE(70);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(72);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 52:
      if (lookahead == 'p') ADVANCE(75);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(76);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 56:
      if (lookahead == 'p') ADVANCE(79);
      END_STATE();
    case 57:
      if (lookahead == 'c') ADVANCE(80);
      END_STATE();
    case 58:
      if (lookahead == 'c') ADVANCE(81);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(82);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_auto);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_bars);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_clip);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(83);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_frag);
      END_STATE();
    case 65:
      if (lookahead == 'p') ADVANCE(84);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_live);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_ramp);
      END_STATE();
    case 70:
      if (lookahead == 'l') ADVANCE(86);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 73:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(90);
      END_STATE();
    case 75:
      if (lookahead == 's') ADVANCE(91);
      END_STATE();
    case 76:
      if (lookahead == 'p') ADVANCE(92);
      END_STATE();
    case 77:
      if (lookahead == 'g') ADVANCE(93);
      END_STATE();
    case 78:
      if (lookahead == 'h') ADVANCE(94);
      END_STATE();
    case 79:
      if (lookahead == 'o') ADVANCE(95);
      END_STATE();
    case 80:
      if (lookahead == 'k') ADVANCE(96);
      END_STATE();
    case 81:
      if (lookahead == 'i') ADVANCE(97);
      END_STATE();
    case 82:
      if (lookahead == 'g') ADVANCE(98);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_drums);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_group);
      END_STATE();
    case 85:
      if (lookahead == 'r') ADVANCE(99);
      END_STATE();
    case 86:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_scale);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_scene);
      END_STATE();
    case 89:
      if (lookahead == 'o') ADVANCE(101);
      END_STATE();
    case 90:
      if (lookahead == 'n') ADVANCE(102);
      END_STATE();
    case 91:
      if (lookahead == 'h') ADVANCE(103);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_strip);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_swing);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_synth);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_tempo);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_track);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(104);
      END_STATE();
    case 98:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_master);
      END_STATE();
    case 100:
      if (lookahead == 'r') ADVANCE(106);
      if (lookahead == 's') ADVANCE(107);
      END_STATE();
    case 101:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 102:
      if (lookahead == 'g') ADVANCE(109);
      END_STATE();
    case 103:
      if (lookahead == 'o') ADVANCE(110);
      END_STATE();
    case 104:
      if (lookahead == 'g') ADVANCE(111);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_arrange);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_sampler);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_samples);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_section);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_setting);
      END_STATE();
    case 110:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_voicing);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_snapshot);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 3, .external_lex_state = 3},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 3, .external_lex_state = 3},
  [5] = {.lex_state = 3, .external_lex_state = 3},
  [6] = {.lex_state = 3, .external_lex_state = 3},
  [7] = {.lex_state = 3, .external_lex_state = 3},
  [8] = {.lex_state = 3, .external_lex_state = 3},
  [9] = {.lex_state = 3, .external_lex_state = 3},
  [10] = {.lex_state = 3, .external_lex_state = 3},
  [11] = {.lex_state = 3, .external_lex_state = 3},
  [12] = {.lex_state = 3, .external_lex_state = 3},
  [13] = {.lex_state = 3, .external_lex_state = 3},
  [14] = {.lex_state = 5, .external_lex_state = 3},
  [15] = {.lex_state = 5, .external_lex_state = 3},
  [16] = {.lex_state = 5, .external_lex_state = 3},
  [17] = {.lex_state = 1, .external_lex_state = 3},
  [18] = {.lex_state = 3, .external_lex_state = 3},
  [19] = {.lex_state = 3, .external_lex_state = 3},
  [20] = {.lex_state = 3, .external_lex_state = 3},
  [21] = {.lex_state = 4, .external_lex_state = 3},
  [22] = {.lex_state = 5, .external_lex_state = 3},
  [23] = {.lex_state = 5, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 4},
  [27] = {.lex_state = 0, .external_lex_state = 4},
  [28] = {.lex_state = 0, .external_lex_state = 4},
  [29] = {.lex_state = 0, .external_lex_state = 4},
  [30] = {.lex_state = 0, .external_lex_state = 4},
  [31] = {.lex_state = 0, .external_lex_state = 4},
  [32] = {.lex_state = 0, .external_lex_state = 4},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 2, .external_lex_state = 3},
  [46] = {.lex_state = 2, .external_lex_state = 3},
  [47] = {.lex_state = 2, .external_lex_state = 3},
  [48] = {.lex_state = 0, .external_lex_state = 3},
  [49] = {.lex_state = 0, .external_lex_state = 3},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0, .external_lex_state = 3},
  [52] = {.lex_state = 0, .external_lex_state = 3},
  [53] = {.lex_state = 0, .external_lex_state = 3},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 0, .external_lex_state = 3},
  [56] = {.lex_state = 0, .external_lex_state = 3},
  [57] = {.lex_state = 0, .external_lex_state = 3},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 0, .external_lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_tempo] = ACTIONS(1),
    [anon_sym_swing] = ACTIONS(1),
    [anon_sym_scale] = ACTIONS(1),
    [anon_sym_setting] = ACTIONS(1),
    [anon_sym_track] = ACTIONS(1),
    [anon_sym_samples] = ACTIONS(1),
    [anon_sym_strip] = ACTIONS(1),
    [anon_sym_group] = ACTIONS(1),
    [anon_sym_master] = ACTIONS(1),
    [anon_sym_clip] = ACTIONS(1),
    [anon_sym_auto] = ACTIONS(1),
    [anon_sym_snapshot] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_scene] = ACTIONS(1),
    [anon_sym_arrange] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_frag] = ACTIONS(1),
    [anon_sym_section] = ACTIONS(1),
    [anon_sym_live] = ACTIONS(1),
    [anon_sym_bars] = ACTIONS(1),
    [anon_sym_ramp] = ACTIONS(1),
    [anon_sym_drums] = ACTIONS(1),
    [anon_sym_synth] = ACTIONS(1),
    [anon_sym_sampler] = ACTIONS(1),
    [anon_sym_voicing] = ACTIONS(1),
    [sym_param] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [sym_punct] = ACTIONS(1),
    [sym_rest] = ACTIONS(1),
    [sym_other] = ACTIONS(1),
    [sym_dots] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__line_start] = ACTIONS(1),
    [sym__modular_start] = ACTIONS(1),
    [sym__lane_indent] = ACTIONS(1),
    [sym__call_lane_indent] = ACTIONS(1),
    [sym__notes_indent] = ACTIONS(1),
    [sym__code_indent] = ACTIONS(1),
    [sym__line_end] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(50),
    [sym_line] = STATE(24),
    [sym_modular] = STATE(24),
    [sym_lane] = STATE(24),
    [sym_notes] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym__line_start] = ACTIONS(7),
    [sym__modular_start] = ACTIONS(9),
    [sym__lane_indent] = ACTIONS(11),
    [sym__call_lane_indent] = ACTIONS(13),
    [sym__notes_indent] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__token] = STATE(6),
    [sym_keyword] = STATE(5),
    [sym_word] = STATE(6),
    [sym_call] = STATE(6),
    [aux_sym_line_repeat1] = STATE(6),
    [sym_name] = ACTIONS(17),
    [anon_sym_tempo] = ACTIONS(19),
    [anon_sym_swing] = ACTIONS(19),
    [anon_sym_scale] = ACTIONS(19),
    [anon_sym_setting] = ACTIONS(19),
    [anon_sym_track] = ACTIONS(19),
    [anon_sym_samples] = ACTIONS(19),
    [anon_sym_strip] = ACTIONS(19),
    [anon_sym_group] = ACTIONS(19),
    [anon_sym_master] = ACTIONS(19),
    [anon_sym_clip] = ACTIONS(19),
    [anon_sym_auto] = ACTIONS(19),
    [anon_sym_snapshot] = ACTIONS(19),
    [anon_sym_mod] = ACTIONS(19),
    [anon_sym_scene] = ACTIONS(19),
    [anon_sym_arrange] = ACTIONS(19),
    [anon_sym_loop] = ACTIONS(19),
    [anon_sym_frag] = ACTIONS(19),
    [anon_sym_section] = ACTIONS(19),
    [anon_sym_live] = ACTIONS(21),
    [anon_sym_bars] = ACTIONS(21),
    [anon_sym_ramp] = ACTIONS(21),
    [anon_sym_drums] = ACTIONS(21),
    [anon_sym_synth] = ACTIONS(21),
    [anon_sym_sampler] = ACTIONS(21),
    [anon_sym_voicing] = ACTIONS(21),
    [sym_param] = ACTIONS(23),
    [sym_number] = ACTIONS(25),
    [sym_punct] = ACTIONS(25),
    [sym_rest] = ACTIONS(25),
    [sym_other] = ACTIONS(27),
    [sym_comment] = ACTIONS(29),
    [sym__line_end] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    STATE(7), 1,
      sym_keyword,
    ACTIONS(33), 18,
      anon_sym_tempo,
      anon_sym_swing,
      anon_sym_scale,
      anon_sym_setting,
      anon_sym_track,
      anon_sym_samples,
      anon_sym_strip,
      anon_sym_group,
      anon_sym_master,
      anon_sym_clip,
      anon_sym_auto,
      anon_sym_snapshot,
      anon_sym_mod,
      anon_sym_scene,
      anon_sym_arrange,
      anon_sym_loop,
      anon_sym_frag,
      anon_sym_section,
  [24] = 8,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(23), 1,
      sym_param,
    ACTIONS(37), 1,
      sym_other,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym__line_end,
    ACTIONS(35), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(9), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(21), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [60] = 8,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(23), 1,
      sym_param,
    ACTIONS(45), 1,
      sym_other,
    ACTIONS(47), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym__line_end,
    ACTIONS(43), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(10), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(21), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [96] = 8,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(23), 1,
      sym_param,
    ACTIONS(47), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym__line_end,
    ACTIONS(53), 1,
      sym_other,
    ACTIONS(51), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(11), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(21), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [132] = 8,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(23), 1,
      sym_param,
    ACTIONS(57), 1,
      sym_other,
    ACTIONS(59), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym__line_end,
    ACTIONS(55), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(12), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(21), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [168] = 8,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(23), 1,
      sym_param,
    ACTIONS(65), 1,
      sym_other,
    ACTIONS(67), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym__line_end,
    ACTIONS(63), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(13), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(21), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [204] = 8,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(23), 1,
      sym_param,
    ACTIONS(53), 1,
      sym_other,
    ACTIONS(71), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym__line_end,
    ACTIONS(51), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(11), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(21), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [240] = 8,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(23), 1,
      sym_param,
    ACTIONS(53), 1,
      sym_other,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym__line_end,
    ACTIONS(51), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(11), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(21), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [276] = 7,
    ACTIONS(79), 1,
      sym_name,
    ACTIONS(85), 1,
      sym_param,
    ACTIONS(91), 1,
      sym_other,
    ACTIONS(94), 2,
      sym__line_end,
      sym_comment,
    ACTIONS(88), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(11), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(82), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [310] = 8,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(23), 1,
      sym_param,
    ACTIONS(53), 1,
      sym_other,
    ACTIONS(96), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym__line_end,
    ACTIONS(51), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(11), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(21), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [346] = 8,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(23), 1,
      sym_param,
    ACTIONS(53), 1,
      sym_other,
    ACTIONS(100), 1,
      sym_comment,
    ACTIONS(102), 1,
      sym__line_end,
    ACTIONS(51), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(11), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(21), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [382] = 7,
    ACTIONS(104), 1,
      sym_name,
    ACTIONS(108), 1,
      sym_param,
    ACTIONS(112), 1,
      sym_other,
    ACTIONS(114), 1,
      sym__line_end,
    ACTIONS(110), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(15), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(106), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [415] = 7,
    ACTIONS(94), 1,
      sym__line_end,
    ACTIONS(116), 1,
      sym_name,
    ACTIONS(122), 1,
      sym_param,
    ACTIONS(128), 1,
      sym_other,
    ACTIONS(125), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(15), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(119), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [448] = 7,
    ACTIONS(104), 1,
      sym_name,
    ACTIONS(108), 1,
      sym_param,
    ACTIONS(133), 1,
      sym_other,
    ACTIONS(135), 1,
      sym__line_end,
    ACTIONS(131), 3,
      sym_number,
      sym_punct,
      sym_rest,
    STATE(14), 4,
      sym__token,
      sym_word,
      sym_call,
      aux_sym_line_repeat1,
    ACTIONS(106), 7,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
  [481] = 3,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 5,
      sym__line_end,
      sym_param,
      sym_number,
      sym_rest,
      sym_comment,
    ACTIONS(137), 10,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
      sym_name,
      sym_punct,
      sym_other,
  [504] = 2,
    ACTIONS(145), 6,
      sym__line_end,
      sym_param,
      sym_number,
      sym_punct,
      sym_rest,
      sym_comment,
    ACTIONS(143), 9,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
      sym_name,
      sym_other,
  [524] = 2,
    ACTIONS(149), 6,
      sym__line_end,
      sym_param,
      sym_number,
      sym_punct,
      sym_rest,
      sym_comment,
    ACTIONS(147), 9,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
      sym_name,
      sym_other,
  [544] = 2,
    ACTIONS(153), 6,
      sym__line_end,
      sym_param,
      sym_number,
      sym_punct,
      sym_rest,
      sym_comment,
    ACTIONS(151), 9,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
      sym_name,
      sym_other,
  [564] = 3,
    ACTIONS(155), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 4,
      sym__line_end,
      sym_param,
      sym_number,
      sym_rest,
    ACTIONS(137), 10,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
      sym_name,
      sym_punct,
      sym_other,
  [586] = 2,
    ACTIONS(149), 5,
      sym__line_end,
      sym_param,
      sym_number,
      sym_punct,
      sym_rest,
    ACTIONS(147), 9,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
      sym_name,
      sym_other,
  [605] = 2,
    ACTIONS(145), 5,
      sym__line_end,
      sym_param,
      sym_number,
      sym_punct,
      sym_rest,
    ACTIONS(143), 9,
      anon_sym_live,
      anon_sym_bars,
      anon_sym_ramp,
      anon_sym_drums,
      anon_sym_synth,
      anon_sym_sampler,
      anon_sym_voicing,
      sym_name,
      sym_other,
  [624] = 8,
    ACTIONS(7), 1,
      sym__line_start,
    ACTIONS(9), 1,
      sym__modular_start,
    ACTIONS(11), 1,
      sym__lane_indent,
    ACTIONS(13), 1,
      sym__call_lane_indent,
    ACTIONS(15), 1,
      sym__notes_indent,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 1,
      anon_sym_LF,
    STATE(25), 5,
      sym_line,
      sym_modular,
      sym_lane,
      sym_notes,
      aux_sym_source_file_repeat1,
  [653] = 8,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(163), 1,
      anon_sym_LF,
    ACTIONS(166), 1,
      sym__line_start,
    ACTIONS(169), 1,
      sym__modular_start,
    ACTIONS(172), 1,
      sym__lane_indent,
    ACTIONS(175), 1,
      sym__call_lane_indent,
    ACTIONS(178), 1,
      sym__notes_indent,
    STATE(25), 5,
      sym_line,
      sym_modular,
      sym_lane,
      sym_notes,
      aux_sym_source_file_repeat1,
  [682] = 4,
    ACTIONS(183), 1,
      anon_sym_LF,
    ACTIONS(185), 1,
      sym__code_indent,
    STATE(27), 2,
      sym_code,
      aux_sym_modular_repeat1,
    ACTIONS(181), 6,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
  [701] = 4,
    ACTIONS(185), 1,
      sym__code_indent,
    ACTIONS(189), 1,
      anon_sym_LF,
    STATE(30), 2,
      sym_code,
      aux_sym_modular_repeat1,
    ACTIONS(187), 6,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
  [720] = 4,
    ACTIONS(185), 1,
      sym__code_indent,
    ACTIONS(191), 1,
      anon_sym_LF,
    STATE(29), 2,
      sym_code,
      aux_sym_modular_repeat1,
    ACTIONS(187), 6,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
  [739] = 4,
    ACTIONS(185), 1,
      sym__code_indent,
    ACTIONS(189), 1,
      anon_sym_LF,
    STATE(30), 2,
      sym_code,
      aux_sym_modular_repeat1,
    ACTIONS(193), 6,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
  [758] = 4,
    ACTIONS(197), 1,
      anon_sym_LF,
    ACTIONS(200), 1,
      sym__code_indent,
    STATE(30), 2,
      sym_code,
      aux_sym_modular_repeat1,
    ACTIONS(195), 6,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
  [777] = 4,
    ACTIONS(185), 1,
      sym__code_indent,
    ACTIONS(189), 1,
      anon_sym_LF,
    STATE(30), 2,
      sym_code,
      aux_sym_modular_repeat1,
    ACTIONS(203), 6,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
  [796] = 4,
    ACTIONS(185), 1,
      sym__code_indent,
    ACTIONS(205), 1,
      anon_sym_LF,
    STATE(31), 2,
      sym_code,
      aux_sym_modular_repeat1,
    ACTIONS(193), 6,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
  [815] = 1,
    ACTIONS(207), 8,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      sym__code_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [826] = 1,
    ACTIONS(209), 8,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      sym__code_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [837] = 1,
    ACTIONS(211), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [847] = 1,
    ACTIONS(213), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [857] = 1,
    ACTIONS(215), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [867] = 1,
    ACTIONS(217), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [877] = 1,
    ACTIONS(219), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [887] = 1,
    ACTIONS(221), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [897] = 1,
    ACTIONS(223), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [907] = 1,
    ACTIONS(225), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [917] = 1,
    ACTIONS(227), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [927] = 1,
    ACTIONS(229), 7,
      sym__line_start,
      sym__modular_start,
      sym__lane_indent,
      sym__call_lane_indent,
      sym__notes_indent,
      ts_builtin_sym_end,
      anon_sym_LF,
  [937] = 3,
    STATE(45), 1,
      aux_sym_lane_repeat1,
    ACTIONS(231), 2,
      sym_step,
      sym_dots,
    ACTIONS(234), 2,
      sym__line_end,
      sym_comment,
  [949] = 4,
    ACTIONS(100), 1,
      sym_comment,
    ACTIONS(102), 1,
      sym__line_end,
    STATE(45), 1,
      aux_sym_lane_repeat1,
    ACTIONS(236), 2,
      sym_step,
      sym_dots,
  [963] = 4,
    ACTIONS(67), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym__line_end,
    STATE(46), 1,
      aux_sym_lane_repeat1,
    ACTIONS(238), 2,
      sym_step,
      sym_dots,
  [977] = 1,
    ACTIONS(240), 1,
      sym__line_end,
  [981] = 1,
    ACTIONS(77), 1,
      sym__line_end,
  [985] = 1,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
  [989] = 1,
    ACTIONS(244), 1,
      sym__line_end,
  [993] = 1,
    ACTIONS(73), 1,
      sym__line_end,
  [997] = 1,
    ACTIONS(246), 1,
      sym__line_end,
  [1001] = 1,
    ACTIONS(248), 1,
      sym_pad,
  [1005] = 1,
    ACTIONS(102), 1,
      sym__line_end,
  [1009] = 1,
    ACTIONS(98), 1,
      sym__line_end,
  [1013] = 1,
    ACTIONS(49), 1,
      sym__line_end,
  [1017] = 1,
    ACTIONS(250), 1,
      sym_pad,
  [1021] = 1,
    ACTIONS(252), 1,
      sym__line_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 24,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 96,
  [SMALL_STATE(7)] = 132,
  [SMALL_STATE(8)] = 168,
  [SMALL_STATE(9)] = 204,
  [SMALL_STATE(10)] = 240,
  [SMALL_STATE(11)] = 276,
  [SMALL_STATE(12)] = 310,
  [SMALL_STATE(13)] = 346,
  [SMALL_STATE(14)] = 382,
  [SMALL_STATE(15)] = 415,
  [SMALL_STATE(16)] = 448,
  [SMALL_STATE(17)] = 481,
  [SMALL_STATE(18)] = 504,
  [SMALL_STATE(19)] = 524,
  [SMALL_STATE(20)] = 544,
  [SMALL_STATE(21)] = 564,
  [SMALL_STATE(22)] = 586,
  [SMALL_STATE(23)] = 605,
  [SMALL_STATE(24)] = 624,
  [SMALL_STATE(25)] = 653,
  [SMALL_STATE(26)] = 682,
  [SMALL_STATE(27)] = 701,
  [SMALL_STATE(28)] = 720,
  [SMALL_STATE(29)] = 739,
  [SMALL_STATE(30)] = 758,
  [SMALL_STATE(31)] = 777,
  [SMALL_STATE(32)] = 796,
  [SMALL_STATE(33)] = 815,
  [SMALL_STATE(34)] = 826,
  [SMALL_STATE(35)] = 837,
  [SMALL_STATE(36)] = 847,
  [SMALL_STATE(37)] = 857,
  [SMALL_STATE(38)] = 867,
  [SMALL_STATE(39)] = 877,
  [SMALL_STATE(40)] = 887,
  [SMALL_STATE(41)] = 897,
  [SMALL_STATE(42)] = 907,
  [SMALL_STATE(43)] = 917,
  [SMALL_STATE(44)] = 927,
  [SMALL_STATE(45)] = 937,
  [SMALL_STATE(46)] = 949,
  [SMALL_STATE(47)] = 963,
  [SMALL_STATE(48)] = 977,
  [SMALL_STATE(49)] = 981,
  [SMALL_STATE(50)] = 985,
  [SMALL_STATE(51)] = 989,
  [SMALL_STATE(52)] = 993,
  [SMALL_STATE(53)] = 997,
  [SMALL_STATE(54)] = 1001,
  [SMALL_STATE(55)] = 1005,
  [SMALL_STATE(56)] = 1009,
  [SMALL_STATE(57)] = 1013,
  [SMALL_STATE(58)] = 1017,
  [SMALL_STATE(59)] = 1021,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modular, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modular, 4, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modular, 5, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_modular_repeat1, 2, 0, 0),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_modular_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_modular_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modular, 6, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notes, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 4, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lane, 4, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notes, 4, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 5, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_notes, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lane, 5, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lane, 3, 0, 0),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lane_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lane_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [242] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__line_start = 0,
  ts_external_token__modular_start = 1,
  ts_external_token__lane_indent = 2,
  ts_external_token__call_lane_indent = 3,
  ts_external_token__notes_indent = 4,
  ts_external_token__code_indent = 5,
  ts_external_token__line_end = 6,
  ts_external_token__error_sentinel = 7,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__line_start] = sym__line_start,
  [ts_external_token__modular_start] = sym__modular_start,
  [ts_external_token__lane_indent] = sym__lane_indent,
  [ts_external_token__call_lane_indent] = sym__call_lane_indent,
  [ts_external_token__notes_indent] = sym__notes_indent,
  [ts_external_token__code_indent] = sym__code_indent,
  [ts_external_token__line_end] = sym__line_end,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__line_start] = true,
    [ts_external_token__modular_start] = true,
    [ts_external_token__lane_indent] = true,
    [ts_external_token__call_lane_indent] = true,
    [ts_external_token__notes_indent] = true,
    [ts_external_token__code_indent] = true,
    [ts_external_token__line_end] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__line_start] = true,
    [ts_external_token__modular_start] = true,
    [ts_external_token__lane_indent] = true,
    [ts_external_token__call_lane_indent] = true,
    [ts_external_token__notes_indent] = true,
  },
  [3] = {
    [ts_external_token__line_end] = true,
  },
  [4] = {
    [ts_external_token__line_start] = true,
    [ts_external_token__modular_start] = true,
    [ts_external_token__lane_indent] = true,
    [ts_external_token__call_lane_indent] = true,
    [ts_external_token__notes_indent] = true,
    [ts_external_token__code_indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_song_external_scanner_create(void);
void tree_sitter_song_external_scanner_destroy(void *);
bool tree_sitter_song_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_song_external_scanner_serialize(void *, char *);
void tree_sitter_song_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_song(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_song_external_scanner_create,
      tree_sitter_song_external_scanner_destroy,
      tree_sitter_song_external_scanner_scan,
      tree_sitter_song_external_scanner_serialize,
      tree_sitter_song_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "song",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
