//! The Oberheim Matrix-12: what the model is and its presets (#330).

use crate::mono::model::{Filter, Hp, MATRIX, MATRIX12};
use crate::mono::preset::Preset;
use crate::params::Param::*;
use crate::synth::{ModelDef, PresetDef};

pub const DEF: ModelDef = ModelDef {
    voices: 12,
    filter: Filter::Ladder(MATRIX),
    slope12: Some(Filter::Svf(MATRIX12)),
    hp: Hp::OnePole,
    has_matrix: true,
    presets: &[
        // A saw and a pulse, a second LFO moving the pulse width and breathing the
        // filter through the matrix: a slow, wide pad.
        PresetDef::of(
            Preset::MatrixPad,
            &[
                (Model, 10.0),
                (Polyphony, 12.0),
                (Analog, 0.5),
                (Vco1Level, 0.8),
                (Vco2Wave, 1.0),
                (Vco2Fine, 7.0),
                (Vco2Level, 0.7),
                (Cutoff, 1_800.0),
                (Resonance, 0.15),
                (Slope, 1.0),
                (AdsrAttack, 0.6),
                (AdsrDecay, 0.7),
                (AdsrSustain, 0.85),
                (AdsrRelease, 1.0),
                (FenvAttack, 0.7),
                (FenvSustain, 0.7),
                (EnvCutoff, 0.2),
                (KeyTrack, 0.5),
                (Lfo2Rate, 0.3),
                (Lfo2Wave, 2.0),
                (Patch1Source, 13.0),
                (Patch1Dest, 4.0),
                (Patch1Amount, 0.35),
                (Patch2Source, 13.0),
                (Patch2Dest, 5.0),
                (Patch2Amount, 0.18),
            ],
        ),
        // A long ramp from every note's start into the cutoff and resonance: the
        // filter sweeps open and the resonance rises as the note ages.
        PresetDef::of(
            Preset::MatrixSweep,
            &[
                (Model, 10.0),
                (Polyphony, 12.0),
                (Analog, 0.4),
                (Vco1Level, 0.9),
                (Vco2Fine, 6.0),
                (Vco2Level, 0.8),
                (Cutoff, 500.0),
                (Resonance, 0.2),
                (Slope, 1.0),
                (AdsrAttack, 0.05),
                (AdsrDecay, 0.5),
                (AdsrSustain, 0.9),
                (AdsrRelease, 0.6),
                (EnvCutoff, 0.0),
                (KeyTrack, 0.6),
                (RampTime, 3.0),
                (Patch1Source, 14.0),
                (Patch1Dest, 5.0),
                (Patch1Amount, 0.7),
                (Patch2Source, 14.0),
                (Patch2Dest, 6.0),
                (Patch2Amount, 0.25),
            ],
        ),
        // Two saws, the filter opened by its envelope and by how hard the key is
        // struck, through the matrix: velocity-sensitive brass.
        PresetDef::of(
            Preset::MatrixBrass,
            &[
                (Model, 10.0),
                (Polyphony, 12.0),
                (Analog, 0.4),
                (Vco1Level, 0.9),
                (Vco2Fine, 8.0),
                (Vco2Level, 0.9),
                (Cutoff, 900.0),
                (Resonance, 0.2),
                (Slope, 1.0),
                (AdsrAttack, 0.05),
                (AdsrDecay, 0.4),
                (AdsrSustain, 0.8),
                (AdsrRelease, 0.25),
                (FenvAttack, 0.07),
                (FenvDecay, 0.5),
                (FenvSustain, 0.55),
                (EnvCutoff, 0.5),
                (KeyTrack, 0.6),
                (Patch1Source, 10.0),
                (Patch1Dest, 5.0),
                (Patch1Amount, 0.4),
            ],
        ),
        // A short third envelope bending the pitch into every note, a sub-heavy
        // saw and a snapping filter: a punchy bass.
        PresetDef::of(
            Preset::MatrixPunch,
            &[
                (Model, 10.0),
                (Polyphony, 12.0),
                (Analog, 0.3),
                (Vco1Coarse, -12.0),
                (Vco1Level, 1.0),
                (Vco2Coarse, -12.0),
                (Vco2Fine, 4.0),
                (Vco2Level, 0.8),
                (Cutoff, 500.0),
                (Resonance, 0.3),
                (Slope, 1.0),
                (AdsrAttack, 0.002),
                (AdsrDecay, 0.3),
                (AdsrSustain, 0.6),
                (AdsrRelease, 0.15),
                (FenvAttack, 0.002),
                (FenvDecay, 0.3),
                (FenvSustain, 0.1),
                (EnvCutoff, 0.6),
                (KeyTrack, 1.0),
                (ArAttack, 0.001),
                (ArRelease, 0.07),
                (Patch1Source, 6.0),
                (Patch1Dest, 1.0),
                (Patch1Amount, 0.5),
                (Patch2Source, 6.0),
                (Patch2Dest, 2.0),
                (Patch2Amount, 0.5),
            ],
        ),
        // VCO 2 frequency-modulating VCO 1 with the third envelope shaping the
        // modulation through the matrix: a struck, clangorous bell.
        PresetDef::of(
            Preset::MatrixBells,
            &[
                (Model, 10.0),
                (Polyphony, 12.0),
                (Analog, 0.3),
                (Vco1Wave, 3.0),
                (Vco1Level, 0.9),
                (Vco2Wave, 3.0),
                (Vco2Coarse, 19.0),
                (Vco2Level, 0.0),
                (XMod, 0.5),
                (Cutoff, 6_000.0),
                (Resonance, 0.1),
                (Slope, 1.0),
                (AdsrAttack, 0.001),
                (AdsrDecay, 1.8),
                (AdsrSustain, 0.0),
                (AdsrRelease, 1.4),
                (KeyTrack, 1.0),
            ],
        ),
        // Unison with a second LFO as the vibrato, delayed by nothing but the wheel:
        // a singing mono-style lead on all twelve voices.
        PresetDef::of(
            Preset::MatrixLead,
            &[
                (Model, 10.0),
                (Polyphony, 12.0),
                (Assign, 1.0),
                (UnisonDetune, 0.12),
                (Analog, 0.4),
                (Vco1Level, 0.9),
                (Vco2Fine, 7.0),
                (Vco2Level, 0.9),
                (Cutoff, 2_800.0),
                (Resonance, 0.3),
                (Slope, 1.0),
                (AdsrAttack, 0.01),
                (AdsrDecay, 0.4),
                (AdsrSustain, 0.8),
                (AdsrRelease, 0.3),
                (FenvAttack, 0.01),
                (FenvSustain, 0.6),
                (EnvCutoff, 0.25),
                (KeyTrack, 0.5),
                (Lfo2Rate, 5.5),
                (Lfo2Wave, 3.0),
                (Patch1Source, 13.0),
                (Patch1Dest, 1.0),
                (Patch1Amount, 0.025),
                (Patch2Source, 13.0),
                (Patch2Dest, 2.0),
                (Patch2Amount, 0.025),
            ],
        ),
    ],
    ..ModelDef::MONO
};
