//! The PPG Wave: what the model is and its presets (#330).

use crate::mono::model::{Filter, PPG};
use crate::mono::preset::Preset;
use crate::params::Param::*;
use crate::synth::{ModelDef, PresetDef};

pub const DEF: ModelDef = ModelDef {
    voices: 8,
    filter: Filter::Ladder(PPG),
    uses_tables: true,
    presets: &[
        // The Sweep table slowly opened by the filter envelope and breathed by the
        // LFO, crossfaded, with chorus II: the sweeping digital pad.
        PresetDef::of(
            Preset::PpgSweepPad,
            &[
                (Polyphony, 8.0),
                (Analog, 0.5),
                (ChorusMode, 2.0),
                (Wt1Table, 0.0),
                (Wt1Pos, 0.15),
                (Vco1Level, 0.8),
                (Wt2Table, 0.0),
                (Wt2Pos, 0.25),
                (Vco2Fine, 7.0),
                (Vco2Level, 0.7),
                (EnvWt, 0.7),
                (LfoWt, 0.1),
                (Cutoff, 3_000.0),
                (Resonance, 0.15),
                (AdsrAttack, 0.9),
                (AdsrDecay, 0.8),
                (AdsrSustain, 0.85),
                (AdsrRelease, 1.0),
                (FenvAttack, 1.4),
                (FenvDecay, 1.0),
                (FenvSustain, 0.6),
                (EnvCutoff, 0.15),
                (KeyTrack, 0.5),
                (LfoWave, 2.0),
                (LfoRate, 0.3),
            ],
        ),
        // The Bell table thrown open at the strike and falling back as the note
        // dies, in digital steps: a glassy bell.
        PresetDef::of(
            Preset::PpgGlassBell,
            &[
                (Polyphony, 8.0),
                (Analog, 0.3),
                (WtSteps, 1.0),
                (Wt1Table, 7.0),
                (Wt1Pos, 0.2),
                (Vco1Level, 0.9),
                (Wt2Table, 7.0),
                (Wt2Pos, 0.1),
                (Vco2Coarse, 12.0),
                (Vco2Level, 0.5),
                (EnvWt, 0.7),
                (Cutoff, 7_000.0),
                (Resonance, 0.1),
                (AdsrAttack, 0.001),
                (AdsrDecay, 1.8),
                (AdsrSustain, 0.0),
                (AdsrRelease, 1.3),
                (FenvAttack, 0.001),
                (FenvDecay, 1.2),
                (FenvSustain, 0.0),
                (EnvCutoff, 0.1),
                (KeyTrack, 1.0),
            ],
        ),
        // The Formant table swept by a slow LFO from oo to ee: a vocal, breathing
        // choir pad.
        PresetDef::of(
            Preset::PpgFormant,
            &[
                (Polyphony, 8.0),
                (Analog, 0.5),
                (ChorusMode, 1.0),
                (Wt1Table, 2.0),
                (Wt1Pos, 0.4),
                (Vco1Level, 0.9),
                (Wt2Table, 2.0),
                (Wt2Pos, 0.45),
                (Vco2Fine, 6.0),
                (Vco2Level, 0.7),
                (LfoWt, 0.35),
                (Cutoff, 4_000.0),
                (Resonance, 0.1),
                (AdsrAttack, 0.5),
                (AdsrDecay, 0.6),
                (AdsrSustain, 0.9),
                (AdsrRelease, 0.8),
                (KeyTrack, 0.5),
                (LfoWave, 2.0),
                (LfoRate, 0.4),
            ],
        ),
        // A pulse table that narrows with the envelope into a low, closing filter:
        // a hollow digital bass.
        PresetDef::of(
            Preset::PpgPulseBass,
            &[
                (Polyphony, 8.0),
                (Analog, 0.3),
                (Wt1Table, 1.0),
                (Wt1Pos, 0.1),
                (Vco1Coarse, -12.0),
                (Vco1Level, 1.0),
                (Wt2Table, 5.0),
                (Wt2Pos, 0.2),
                (Vco2Coarse, -12.0),
                (Vco2Fine, 5.0),
                (Vco2Level, 0.7),
                (EnvWt, 0.5),
                (Cutoff, 700.0),
                (Resonance, 0.3),
                (Drive, 0.2),
                (AdsrAttack, 0.002),
                (AdsrDecay, 0.4),
                (AdsrSustain, 0.7),
                (AdsrRelease, 0.15),
                (FenvAttack, 0.002),
                (FenvDecay, 0.3),
                (FenvSustain, 0.1),
                (EnvCutoff, 0.6),
                (KeyTrack, 1.0),
            ],
        ),
        // The seeded Digital table in steps, closing quickly: a gritty, stepped
        // pluck.
        PresetDef::of(
            Preset::PpgDigitalPluck,
            &[
                (Polyphony, 8.0),
                (Analog, 0.3),
                (WtSteps, 1.0),
                (Wt1Table, 6.0),
                (Wt1Pos, 0.6),
                (Vco1Level, 1.0),
                (Wt2Table, 6.0),
                (Wt2Pos, 0.3),
                (Vco2Coarse, 12.0),
                (Vco2Level, 0.5),
                (EnvWt, -0.5),
                (Cutoff, 2_500.0),
                (Resonance, 0.25),
                (AdsrAttack, 0.001),
                (AdsrDecay, 0.5),
                (AdsrSustain, 0.0),
                (AdsrRelease, 0.3),
                (FenvAttack, 0.001),
                (FenvDecay, 0.35),
                (FenvSustain, 0.0),
                (EnvCutoff, 0.5),
                (KeyTrack, 0.8),
            ],
        ),
        // The Organ table with the LFO shifting its drawbars, chorus I: a moving,
        // wave-organ pad.
        PresetDef::of(
            Preset::PpgOrganWave,
            &[
                (Polyphony, 8.0),
                (Analog, 0.4),
                (ChorusMode, 1.0),
                (Wt1Table, 4.0),
                (Wt1Pos, 0.5),
                (Vco1Level, 0.9),
                (Wt2Table, 4.0),
                (Wt2Pos, 0.2),
                (Vco2Coarse, 12.0),
                (Vco2Level, 0.4),
                (LfoWt, 0.4),
                (Cutoff, 5_000.0),
                (Resonance, 0.05),
                (AdsrAttack, 0.02),
                (AdsrDecay, 0.3),
                (AdsrSustain, 0.9),
                (AdsrRelease, 0.3),
                (KeyTrack, 0.5),
                (LfoWave, 2.0),
                (LfoRate, 0.7),
            ],
        ),
    ],
    ..ModelDef::MONO
};
